// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: minidfs.proto

package minidfs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniDFSService_ListFiles_FullMethodName          = "/minidfs.MiniDFSService/ListFiles"
	MiniDFSService_StoreFile_FullMethodName          = "/minidfs.MiniDFSService/StoreFile"
	MiniDFSService_FetchFile_FullMethodName          = "/minidfs.MiniDFSService/FetchFile"
	MiniDFSService_GetFileLock_FullMethodName        = "/minidfs.MiniDFSService/GetFileLock"
	MiniDFSService_RemoveFile_FullMethodName         = "/minidfs.MiniDFSService/RemoveFile"
	MiniDFSService_FileUpdateCallback_FullMethodName = "/minidfs.MiniDFSService/FileUpdateCallback"
)

// MiniDFSServiceClient is the client API for MiniDFSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service methods for minidfs
type MiniDFSServiceClient interface {
	// List files in a directory
	ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesRes, error)
	// Store files on the server
	StoreFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileBuffer, StoreFileRes], error)
	// Fetch files from the server
	FetchFile(ctx context.Context, in *FetchFileReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileBuffer], error)
	// Get a file lock
	GetFileLock(ctx context.Context, in *FileLockReq, opts ...grpc.CallOption) (*FileLockRes, error)
	// Delete file request
	RemoveFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileRes, error)
	// Callback for file updates
	FileUpdateCallback(ctx context.Context, in *FileUpdate, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileUpdate], error)
}

type miniDFSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniDFSServiceClient(cc grpc.ClientConnInterface) MiniDFSServiceClient {
	return &miniDFSServiceClient{cc}
}

func (c *miniDFSServiceClient) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesRes)
	err := c.cc.Invoke(ctx, MiniDFSService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniDFSServiceClient) StoreFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileBuffer, StoreFileRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MiniDFSService_ServiceDesc.Streams[0], MiniDFSService_StoreFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileBuffer, StoreFileRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniDFSService_StoreFileClient = grpc.ClientStreamingClient[FileBuffer, StoreFileRes]

func (c *miniDFSServiceClient) FetchFile(ctx context.Context, in *FetchFileReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileBuffer], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MiniDFSService_ServiceDesc.Streams[1], MiniDFSService_FetchFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchFileReq, FileBuffer]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniDFSService_FetchFileClient = grpc.ServerStreamingClient[FileBuffer]

func (c *miniDFSServiceClient) GetFileLock(ctx context.Context, in *FileLockReq, opts ...grpc.CallOption) (*FileLockRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileLockRes)
	err := c.cc.Invoke(ctx, MiniDFSService_GetFileLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniDFSServiceClient) RemoveFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileRes)
	err := c.cc.Invoke(ctx, MiniDFSService_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniDFSServiceClient) FileUpdateCallback(ctx context.Context, in *FileUpdate, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MiniDFSService_ServiceDesc.Streams[2], MiniDFSService_FileUpdateCallback_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileUpdate, FileUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniDFSService_FileUpdateCallbackClient = grpc.ServerStreamingClient[FileUpdate]

// MiniDFSServiceServer is the server API for MiniDFSService service.
// All implementations must embed UnimplementedMiniDFSServiceServer
// for forward compatibility.
//
// service methods for minidfs
type MiniDFSServiceServer interface {
	// List files in a directory
	ListFiles(context.Context, *ListFilesReq) (*ListFilesRes, error)
	// Store files on the server
	StoreFile(grpc.ClientStreamingServer[FileBuffer, StoreFileRes]) error
	// Fetch files from the server
	FetchFile(*FetchFileReq, grpc.ServerStreamingServer[FileBuffer]) error
	// Get a file lock
	GetFileLock(context.Context, *FileLockReq) (*FileLockRes, error)
	// Delete file request
	RemoveFile(context.Context, *DeleteFileReq) (*DeleteFileRes, error)
	// Callback for file updates
	FileUpdateCallback(*FileUpdate, grpc.ServerStreamingServer[FileUpdate]) error
	mustEmbedUnimplementedMiniDFSServiceServer()
}

// UnimplementedMiniDFSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniDFSServiceServer struct{}

func (UnimplementedMiniDFSServiceServer) ListFiles(context.Context, *ListFilesReq) (*ListFilesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedMiniDFSServiceServer) StoreFile(grpc.ClientStreamingServer[FileBuffer, StoreFileRes]) error {
	return status.Error(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedMiniDFSServiceServer) FetchFile(*FetchFileReq, grpc.ServerStreamingServer[FileBuffer]) error {
	return status.Error(codes.Unimplemented, "method FetchFile not implemented")
}
func (UnimplementedMiniDFSServiceServer) GetFileLock(context.Context, *FileLockReq) (*FileLockRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileLock not implemented")
}
func (UnimplementedMiniDFSServiceServer) RemoveFile(context.Context, *DeleteFileReq) (*DeleteFileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedMiniDFSServiceServer) FileUpdateCallback(*FileUpdate, grpc.ServerStreamingServer[FileUpdate]) error {
	return status.Error(codes.Unimplemented, "method FileUpdateCallback not implemented")
}
func (UnimplementedMiniDFSServiceServer) mustEmbedUnimplementedMiniDFSServiceServer() {}
func (UnimplementedMiniDFSServiceServer) testEmbeddedByValue()                        {}

// UnsafeMiniDFSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniDFSServiceServer will
// result in compilation errors.
type UnsafeMiniDFSServiceServer interface {
	mustEmbedUnimplementedMiniDFSServiceServer()
}

func RegisterMiniDFSServiceServer(s grpc.ServiceRegistrar, srv MiniDFSServiceServer) {
	// If the following call panics, it indicates UnimplementedMiniDFSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniDFSService_ServiceDesc, srv)
}

func _MiniDFSService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniDFSServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniDFSService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniDFSServiceServer).ListFiles(ctx, req.(*ListFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniDFSService_StoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MiniDFSServiceServer).StoreFile(&grpc.GenericServerStream[FileBuffer, StoreFileRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniDFSService_StoreFileServer = grpc.ClientStreamingServer[FileBuffer, StoreFileRes]

func _MiniDFSService_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchFileReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MiniDFSServiceServer).FetchFile(m, &grpc.GenericServerStream[FetchFileReq, FileBuffer]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniDFSService_FetchFileServer = grpc.ServerStreamingServer[FileBuffer]

func _MiniDFSService_GetFileLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileLockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniDFSServiceServer).GetFileLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniDFSService_GetFileLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniDFSServiceServer).GetFileLock(ctx, req.(*FileLockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniDFSService_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniDFSServiceServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniDFSService_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniDFSServiceServer).RemoveFile(ctx, req.(*DeleteFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniDFSService_FileUpdateCallback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileUpdate)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MiniDFSServiceServer).FileUpdateCallback(m, &grpc.GenericServerStream[FileUpdate, FileUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniDFSService_FileUpdateCallbackServer = grpc.ServerStreamingServer[FileUpdate]

// MiniDFSService_ServiceDesc is the grpc.ServiceDesc for MiniDFSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniDFSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minidfs.MiniDFSService",
	HandlerType: (*MiniDFSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFiles",
			Handler:    _MiniDFSService_ListFiles_Handler,
		},
		{
			MethodName: "GetFileLock",
			Handler:    _MiniDFSService_GetFileLock_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _MiniDFSService_RemoveFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreFile",
			Handler:       _MiniDFSService_StoreFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchFile",
			Handler:       _MiniDFSService_FetchFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileUpdateCallback",
			Handler:       _MiniDFSService_FileUpdateCallback_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "minidfs.proto",
}
