// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: minidfs.proto

#include "minidfs.pb.h"
#include "minidfs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace minidfs {

static const char* MiniDFSService_method_names[] = {
  "/minidfs.MiniDFSService/ListFiles",
  "/minidfs.MiniDFSService/StoreFile",
  "/minidfs.MiniDFSService/FetchFile",
  "/minidfs.MiniDFSService/GetFileLock",
  "/minidfs.MiniDFSService/RemoveFile",
  "/minidfs.MiniDFSService/FileUpdateCallback",
};

std::unique_ptr< MiniDFSService::Stub> MiniDFSService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MiniDFSService::Stub> stub(new MiniDFSService::Stub(channel, options));
  return stub;
}

MiniDFSService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListFiles_(MiniDFSService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StoreFile_(MiniDFSService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_FetchFile_(MiniDFSService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetFileLock_(MiniDFSService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoveFile_(MiniDFSService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FileUpdateCallback_(MiniDFSService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MiniDFSService::Stub::ListFiles(::grpc::ClientContext* context, const ::minidfs::ListFilesReq& request, ::minidfs::ListFilesRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::ListFilesReq, ::minidfs::ListFilesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListFiles_, context, request, response);
}

void MiniDFSService::Stub::async::ListFiles(::grpc::ClientContext* context, const ::minidfs::ListFilesReq* request, ::minidfs::ListFilesRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::ListFilesReq, ::minidfs::ListFilesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListFiles_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::ListFiles(::grpc::ClientContext* context, const ::minidfs::ListFilesReq* request, ::minidfs::ListFilesRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListFiles_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::ListFilesRes>* MiniDFSService::Stub::PrepareAsyncListFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListFilesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::ListFilesRes, ::minidfs::ListFilesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListFiles_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::ListFilesRes>* MiniDFSService::Stub::AsyncListFilesRaw(::grpc::ClientContext* context, const ::minidfs::ListFilesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListFilesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::minidfs::FileBuffer>* MiniDFSService::Stub::StoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response) {
  return ::grpc::internal::ClientWriterFactory< ::minidfs::FileBuffer>::Create(channel_.get(), rpcmethod_StoreFile_, context, response);
}

void MiniDFSService::Stub::async::StoreFile(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::ClientWriteReactor< ::minidfs::FileBuffer>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::minidfs::FileBuffer>::Create(stub_->channel_.get(), stub_->rpcmethod_StoreFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>* MiniDFSService::Stub::AsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_StoreFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::minidfs::FileBuffer>* MiniDFSService::Stub::PrepareAsyncStoreFileRaw(::grpc::ClientContext* context, ::minidfs::StoreFileRes* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_StoreFile_, context, response, false, nullptr);
}

::grpc::ClientReader< ::minidfs::FileBuffer>* MiniDFSService::Stub::FetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::minidfs::FileBuffer>::Create(channel_.get(), rpcmethod_FetchFile_, context, request);
}

void MiniDFSService::Stub::async::FetchFile(::grpc::ClientContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ClientReadReactor< ::minidfs::FileBuffer>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::minidfs::FileBuffer>::Create(stub_->channel_.get(), stub_->rpcmethod_FetchFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::minidfs::FileBuffer>* MiniDFSService::Stub::AsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_FetchFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::minidfs::FileBuffer>* MiniDFSService::Stub::PrepareAsyncFetchFileRaw(::grpc::ClientContext* context, const ::minidfs::FetchFileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::minidfs::FileBuffer>::Create(channel_.get(), cq, rpcmethod_FetchFile_, context, request, false, nullptr);
}

::grpc::Status MiniDFSService::Stub::GetFileLock(::grpc::ClientContext* context, const ::minidfs::FileLockReq& request, ::minidfs::FileLockRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::FileLockReq, ::minidfs::FileLockRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFileLock_, context, request, response);
}

void MiniDFSService::Stub::async::GetFileLock(::grpc::ClientContext* context, const ::minidfs::FileLockReq* request, ::minidfs::FileLockRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::FileLockReq, ::minidfs::FileLockRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileLock_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::GetFileLock(::grpc::ClientContext* context, const ::minidfs::FileLockReq* request, ::minidfs::FileLockRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileLock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::FileLockRes>* MiniDFSService::Stub::PrepareAsyncGetFileLockRaw(::grpc::ClientContext* context, const ::minidfs::FileLockReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::FileLockRes, ::minidfs::FileLockReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFileLock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::FileLockRes>* MiniDFSService::Stub::AsyncGetFileLockRaw(::grpc::ClientContext* context, const ::minidfs::FileLockReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFileLockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MiniDFSService::Stub::RemoveFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::minidfs::DeleteFileRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RemoveFile_, context, request, response);
}

void MiniDFSService::Stub::async::RemoveFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveFile_, context, request, response, std::move(f));
}

void MiniDFSService::Stub::async::RemoveFile(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>* MiniDFSService::Stub::PrepareAsyncRemoveFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::minidfs::DeleteFileRes, ::minidfs::DeleteFileReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RemoveFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::minidfs::DeleteFileRes>* MiniDFSService::Stub::AsyncRemoveFileRaw(::grpc::ClientContext* context, const ::minidfs::DeleteFileReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemoveFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::minidfs::FileUpdate>* MiniDFSService::Stub::FileUpdateCallbackRaw(::grpc::ClientContext* context, const ::minidfs::FileUpdate& request) {
  return ::grpc::internal::ClientReaderFactory< ::minidfs::FileUpdate>::Create(channel_.get(), rpcmethod_FileUpdateCallback_, context, request);
}

void MiniDFSService::Stub::async::FileUpdateCallback(::grpc::ClientContext* context, const ::minidfs::FileUpdate* request, ::grpc::ClientReadReactor< ::minidfs::FileUpdate>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::minidfs::FileUpdate>::Create(stub_->channel_.get(), stub_->rpcmethod_FileUpdateCallback_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::minidfs::FileUpdate>* MiniDFSService::Stub::AsyncFileUpdateCallbackRaw(::grpc::ClientContext* context, const ::minidfs::FileUpdate& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::minidfs::FileUpdate>::Create(channel_.get(), cq, rpcmethod_FileUpdateCallback_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::minidfs::FileUpdate>* MiniDFSService::Stub::PrepareAsyncFileUpdateCallbackRaw(::grpc::ClientContext* context, const ::minidfs::FileUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::minidfs::FileUpdate>::Create(channel_.get(), cq, rpcmethod_FileUpdateCallback_, context, request, false, nullptr);
}

MiniDFSService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::ListFilesReq, ::minidfs::ListFilesRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::ListFilesReq* req,
             ::minidfs::ListFilesRes* resp) {
               return service->ListFiles(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< MiniDFSService::Service, ::minidfs::FileBuffer, ::minidfs::StoreFileRes>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::minidfs::FileBuffer>* reader,
             ::minidfs::StoreFileRes* resp) {
               return service->StoreFile(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MiniDFSService::Service, ::minidfs::FetchFileReq, ::minidfs::FileBuffer>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::FetchFileReq* req,
             ::grpc::ServerWriter<::minidfs::FileBuffer>* writer) {
               return service->FetchFile(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::FileLockReq, ::minidfs::FileLockRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::FileLockReq* req,
             ::minidfs::FileLockRes* resp) {
               return service->GetFileLock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MiniDFSService::Service, ::minidfs::DeleteFileReq, ::minidfs::DeleteFileRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::DeleteFileReq* req,
             ::minidfs::DeleteFileRes* resp) {
               return service->RemoveFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MiniDFSService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MiniDFSService::Service, ::minidfs::FileUpdate, ::minidfs::FileUpdate>(
          [](MiniDFSService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::minidfs::FileUpdate* req,
             ::grpc::ServerWriter<::minidfs::FileUpdate>* writer) {
               return service->FileUpdateCallback(ctx, req, writer);
             }, this)));
}

MiniDFSService::Service::~Service() {
}

::grpc::Status MiniDFSService::Service::ListFiles(::grpc::ServerContext* context, const ::minidfs::ListFilesReq* request, ::minidfs::ListFilesRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::StoreFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::minidfs::FileBuffer>* reader, ::minidfs::StoreFileRes* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::FetchFile(::grpc::ServerContext* context, const ::minidfs::FetchFileReq* request, ::grpc::ServerWriter< ::minidfs::FileBuffer>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::GetFileLock(::grpc::ServerContext* context, const ::minidfs::FileLockReq* request, ::minidfs::FileLockRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::RemoveFile(::grpc::ServerContext* context, const ::minidfs::DeleteFileReq* request, ::minidfs::DeleteFileRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MiniDFSService::Service::FileUpdateCallback(::grpc::ServerContext* context, const ::minidfs::FileUpdate* request, ::grpc::ServerWriter< ::minidfs::FileUpdate>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace minidfs

